### ISSUE TITLE
Mapa mental 

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Paola939#2]
[Mapa Mental_ Paola Rosario.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Paola939/files/12679649/Mapa.Mental_.Paola.Rosario.pdf)

**Comment by DanAlejandr** [comment]
Manejo conceptual: 25%
Relación entre los conjuntos: 25%
Calidad de la presentación: 25%
Jerarquía: 25%
Total 20/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..de bv...
